### PR TITLE
test(account): add login form error state checks

### LINKED ISSUE #3: Add error state check for login form
Implement error state checks fro login form

1. Use `Fetch all remotes` and then `Update` branch `master` in IDEA.
2. Create a new branch with name `test-#<issue_number>/add-login-form-error-state-checks` from the latest commit in the `master` branch. (Right click -> New branch...)
3. Add new test class `LoginFormErrorStateTest` similar to the `LoginTest`
4. Add all necessary @before, @after methods
5. Implement tests for these cases:
- When email and password fields are empty, user can't click on `Sign in` button
- When user enters only email or password, user can't click on `Sign in` button
- When user enters incorrect email, i.e. without `@` or without domain part after `@`, email field changes color.
6. Add commit with name `test(account): add login form error state checks`
7. Add PR with similar name and body `closes #<issue_number>`

Try to extract expected results and string variables into constants. 
Try to use `Assert` methods to check for the expected results.
Implement different test cases as different methods.

Bonus:
Structure your test methods in AAA paradigm and decorate them with comments:
```
// Arrange
... here goes the test case preparation code

// Act
... here goes actions for test case: entering the text in input fields, clicking the buttons etc

// Assert
... here we check the result vs expected ones.
```

### PR DESCRIPTION
**Pull request by KateGPS**
closes #3

### CODE REVIEW

File: src/test/java/LoginFormErrorStateTest.java [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+    private WebDriver driver;
+
+    @BeforeSuite
+    public void setupDriverManager() {
+        WebDriverManager.chromedriver().setup();
+    }
+
+    @BeforeTest
+    public void openBrowser() {
+        this.driver = new ChromeDriver();
```
Comment (sapozhnikovay) [inline src/test/java/LoginFormErrorStateTest.java]: Please  don't use `this.` keyword for class variables. The same is for `closeBrowser` method.

File: src/test/java/LoginFormErrorStateTest.java [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+
+    }
+
+    @AfterTest
+    public void closeBrowser() {
+        this.driver.quit();
+    }
+
+    @Test
+    public void LoginWithoutLoginPassword() {
```
Comment (sapozhnikovay) [inline src/test/java/LoginFormErrorStateTest.java]: imo `LoginWithoutEmailAndPassword` is more descriptive

File: src/test/java/LoginFormErrorStateTest.java [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+
+        // Arrange
+        driver.get("https://app.neuralegion.com/login");
+
+        //Assert
+        WebElement submit = driver.findElement(By.cssSelector("auth-login-form form > button"));
+        Assert.assertEquals(false, submit.isEnabled());
```
Comment (sapozhnikovay) [inline src/test/java/LoginFormErrorStateTest.java]: Please check and adjust the order of arguments here and below in `Assert` calls. First one is `actual value`, the second - `expected value`. With wrong order we'll get the wrong error message in case of test failure.

File: src/test/java/LoginFormErrorStateTest.java [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+    }
+
+    @Test
+    public void LoginWithoutLoginPassword() {
+
+        // Arrange
+        driver.get("https://app.neuralegion.com/login");
+
+        //Assert
+        WebElement submit = driver.findElement(By.cssSelector("auth-login-form form > button"));
```
Comment (sapozhnikovay) [inline src/test/java/LoginFormErrorStateTest.java]: I think we should name the variables more precise. `submitButton` is more descriptive imo. `emailInput` is better than simply `email`. Please check and adjust here and below.

File: src/test/java/LoginFormErrorStateTest.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+        // Assert
+        WebElement emailField = driver.findElement(By.cssSelector("auth-login-form form > mat-form-field .mat-form-field-outline-thick"));
+
+        String emailFieldBorderColor = Color.fromString(emailField.getCssValue("color")).asHex();
+        final String expectedBorderColor = "#995e00";
+        Assert.assertEquals(emailFieldBorderColor, expectedBorderColor);
+    }
+
+    @Test
+    public void LoginWithIncorrectEmail2() {
```
Comment (sapozhnikovay) [inline src/test/java/LoginFormErrorStateTest.java]: The name of this test method is not descriptive. Please adjust it to something like `LoginWithEmailWithoutAtSymbol`. So it can be easily distinguished in the test report in case of an error.

**Review by sapozhnikovay — CHANGES_REQUESTED** [review]
Good job! 💪

Please, address some naming issues below.

File: src/test/java/LoginFormErrorStateTest.java (hunk 1 above)
Comment (KateGPS) [reply src/test/java/LoginFormErrorStateTest.java]: Could we just use "driver" in this case or we need to replace it with another word?

Comment (sapozhnikovay) [reply src/test/java/LoginFormErrorStateTest.java]: yep, `driver` looks good to me.
